// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/grpc/proto/record.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Password struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Password) Reset() {
	*x = Password{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Password) ProtoMessage() {}

func (x *Password) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Password.ProtoReflect.Descriptor instead.
func (*Password) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{0}
}

func (x *Password) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Password) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{1}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Binary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Binary) Reset() {
	*x = Binary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Binary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binary) ProtoMessage() {}

func (x *Binary) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binary.ProtoReflect.Descriptor instead.
func (*Binary) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{2}
}

func (x *Binary) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number  string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Expired string `protobuf:"bytes,3,opt,name=expired,proto3" json:"expired,omitempty"`
	Csv     string `protobuf:"bytes,4,opt,name=csv,proto3" json:"csv,omitempty"`
	Holder  string `protobuf:"bytes,5,opt,name=holder,proto3" json:"holder,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetExpired() string {
	if x != nil {
		return x.Expired
	}
	return ""
}

func (x *Card) GetCsv() string {
	if x != nil {
		return x.Csv
	}
	return ""
}

func (x *Card) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Record:
	//	*Record_Password
	//	*Record_Text
	//	*Record_Binary
	//	*Record_Card
	Record isRecord_Record `protobuf_oneof:"record"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{4}
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *Record) GetRecord() isRecord_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *Record) GetPassword() *Password {
	if x, ok := x.GetRecord().(*Record_Password); ok {
		return x.Password
	}
	return nil
}

func (x *Record) GetText() *Text {
	if x, ok := x.GetRecord().(*Record_Text); ok {
		return x.Text
	}
	return nil
}

func (x *Record) GetBinary() *Binary {
	if x, ok := x.GetRecord().(*Record_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *Record) GetCard() *Card {
	if x, ok := x.GetRecord().(*Record_Card); ok {
		return x.Card
	}
	return nil
}

type isRecord_Record interface {
	isRecord_Record()
}

type Record_Password struct {
	Password *Password `protobuf:"bytes,4,opt,name=password,proto3,oneof"`
}

type Record_Text struct {
	Text *Text `protobuf:"bytes,5,opt,name=text,proto3,oneof"`
}

type Record_Binary struct {
	Binary *Binary `protobuf:"bytes,6,opt,name=binary,proto3,oneof"`
}

type Record_Card struct {
	Card *Card `protobuf:"bytes,7,opt,name=card,proto3,oneof"`
}

func (*Record_Password) isRecord_Record() {}

func (*Record_Text) isRecord_Record() {}

func (*Record_Binary) isRecord_Record() {}

func (*Record_Card) isRecord_Record() {}

type RecordCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Record:
	//	*RecordCreateRequest_Password
	//	*RecordCreateRequest_Text
	//	*RecordCreateRequest_Binary
	//	*RecordCreateRequest_Card
	Record isRecordCreateRequest_Record `protobuf_oneof:"record"`
}

func (x *RecordCreateRequest) Reset() {
	*x = RecordCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCreateRequest) ProtoMessage() {}

func (x *RecordCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCreateRequest.ProtoReflect.Descriptor instead.
func (*RecordCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{5}
}

func (x *RecordCreateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (m *RecordCreateRequest) GetRecord() isRecordCreateRequest_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *RecordCreateRequest) GetPassword() *Password {
	if x, ok := x.GetRecord().(*RecordCreateRequest_Password); ok {
		return x.Password
	}
	return nil
}

func (x *RecordCreateRequest) GetText() *Text {
	if x, ok := x.GetRecord().(*RecordCreateRequest_Text); ok {
		return x.Text
	}
	return nil
}

func (x *RecordCreateRequest) GetBinary() *Binary {
	if x, ok := x.GetRecord().(*RecordCreateRequest_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *RecordCreateRequest) GetCard() *Card {
	if x, ok := x.GetRecord().(*RecordCreateRequest_Card); ok {
		return x.Card
	}
	return nil
}

type isRecordCreateRequest_Record interface {
	isRecordCreateRequest_Record()
}

type RecordCreateRequest_Password struct {
	Password *Password `protobuf:"bytes,2,opt,name=password,proto3,oneof"`
}

type RecordCreateRequest_Text struct {
	Text *Text `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type RecordCreateRequest_Binary struct {
	Binary *Binary `protobuf:"bytes,4,opt,name=binary,proto3,oneof"`
}

type RecordCreateRequest_Card struct {
	Card *Card `protobuf:"bytes,5,opt,name=card,proto3,oneof"`
}

func (*RecordCreateRequest_Password) isRecordCreateRequest_Record() {}

func (*RecordCreateRequest_Text) isRecordCreateRequest_Record() {}

func (*RecordCreateRequest_Binary) isRecordCreateRequest_Record() {}

func (*RecordCreateRequest_Card) isRecordCreateRequest_Record() {}

type RecordUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Record:
	//	*RecordUpdateRequest_Password
	//	*RecordUpdateRequest_Text
	//	*RecordUpdateRequest_Binary
	//	*RecordUpdateRequest_Card
	Record isRecordUpdateRequest_Record `protobuf_oneof:"record"`
}

func (x *RecordUpdateRequest) Reset() {
	*x = RecordUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUpdateRequest) ProtoMessage() {}

func (x *RecordUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUpdateRequest.ProtoReflect.Descriptor instead.
func (*RecordUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{6}
}

func (x *RecordUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordUpdateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (m *RecordUpdateRequest) GetRecord() isRecordUpdateRequest_Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (x *RecordUpdateRequest) GetPassword() *Password {
	if x, ok := x.GetRecord().(*RecordUpdateRequest_Password); ok {
		return x.Password
	}
	return nil
}

func (x *RecordUpdateRequest) GetText() *Text {
	if x, ok := x.GetRecord().(*RecordUpdateRequest_Text); ok {
		return x.Text
	}
	return nil
}

func (x *RecordUpdateRequest) GetBinary() *Binary {
	if x, ok := x.GetRecord().(*RecordUpdateRequest_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *RecordUpdateRequest) GetCard() *Card {
	if x, ok := x.GetRecord().(*RecordUpdateRequest_Card); ok {
		return x.Card
	}
	return nil
}

type isRecordUpdateRequest_Record interface {
	isRecordUpdateRequest_Record()
}

type RecordUpdateRequest_Password struct {
	Password *Password `protobuf:"bytes,3,opt,name=password,proto3,oneof"`
}

type RecordUpdateRequest_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type RecordUpdateRequest_Binary struct {
	Binary *Binary `protobuf:"bytes,5,opt,name=binary,proto3,oneof"`
}

type RecordUpdateRequest_Card struct {
	Card *Card `protobuf:"bytes,6,opt,name=card,proto3,oneof"`
}

func (*RecordUpdateRequest_Password) isRecordUpdateRequest_Record() {}

func (*RecordUpdateRequest_Text) isRecordUpdateRequest_Record() {}

func (*RecordUpdateRequest_Binary) isRecordUpdateRequest_Record() {}

func (*RecordUpdateRequest_Card) isRecordUpdateRequest_Record() {}

type RecordDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RecordDeleteRequest) Reset() {
	*x = RecordDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDeleteRequest) ProtoMessage() {}

func (x *RecordDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDeleteRequest.ProtoReflect.Descriptor instead.
func (*RecordDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{7}
}

func (x *RecordDeleteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RecordDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecordGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RecordGetRequest) Reset() {
	*x = RecordGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordGetRequest) ProtoMessage() {}

func (x *RecordGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordGetRequest.ProtoReflect.Descriptor instead.
func (*RecordGetRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{8}
}

func (x *RecordGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordGetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RecordCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RecordCreatedResponse) Reset() {
	*x = RecordCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordCreatedResponse) ProtoMessage() {}

func (x *RecordCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordCreatedResponse.ProtoReflect.Descriptor instead.
func (*RecordCreatedResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{9}
}

func (x *RecordCreatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordCreatedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RecordUpdatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RecordUpdatedResponse) Reset() {
	*x = RecordUpdatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordUpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUpdatedResponse) ProtoMessage() {}

func (x *RecordUpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUpdatedResponse.ProtoReflect.Descriptor instead.
func (*RecordUpdatedResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{10}
}

func (x *RecordUpdatedResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordUpdatedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RecordDeletedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RecordDeletedResponse) Reset() {
	*x = RecordDeletedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordDeletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDeletedResponse) ProtoMessage() {}

func (x *RecordDeletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDeletedResponse.ProtoReflect.Descriptor instead.
func (*RecordDeletedResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{11}
}

func (x *RecordDeletedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{12}
}

func (x *RecordResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type RecordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *RecordsResponse) Reset() {
	*x = RecordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_record_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsResponse) ProtoMessage() {}

func (x *RecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_record_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsResponse.ProtoReflect.Descriptor instead.
func (*RecordsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_record_proto_rawDescGZIP(), []int{13}
}

func (x *RecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_api_grpc_proto_record_proto protoreflect.FileDescriptor

var file_api_grpc_proto_record_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x3c, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x1c, 0x0a, 0x06, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a,
	0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x73, 0x76, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x73, 0x76, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x22, 0xec, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x54, 0x65, 0x78, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x48, 0x00,
	0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x22, 0xd7, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x22,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x42, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x48, 0x00, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0xe7, 0x01, 0x0a, 0x13, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x48, 0x00, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x22, 0x3b, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x38, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a, 0x15, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3d, 0x0a, 0x15, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x15, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x22, 0x3b, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x32,
	0xf5, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x18, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x1d, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x17,
	0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_grpc_proto_record_proto_rawDescOnce sync.Once
	file_api_grpc_proto_record_proto_rawDescData = file_api_grpc_proto_record_proto_rawDesc
)

func file_api_grpc_proto_record_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_record_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_record_proto_rawDescData)
	})
	return file_api_grpc_proto_record_proto_rawDescData
}

var file_api_grpc_proto_record_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_grpc_proto_record_proto_goTypes = []interface{}{
	(*Password)(nil),              // 0: record.Password
	(*Text)(nil),                  // 1: record.Text
	(*Binary)(nil),                // 2: record.Binary
	(*Card)(nil),                  // 3: record.Card
	(*Record)(nil),                // 4: record.Record
	(*RecordCreateRequest)(nil),   // 5: record.RecordCreateRequest
	(*RecordUpdateRequest)(nil),   // 6: record.RecordUpdateRequest
	(*RecordDeleteRequest)(nil),   // 7: record.RecordDeleteRequest
	(*RecordGetRequest)(nil),      // 8: record.RecordGetRequest
	(*RecordCreatedResponse)(nil), // 9: record.RecordCreatedResponse
	(*RecordUpdatedResponse)(nil), // 10: record.RecordUpdatedResponse
	(*RecordDeletedResponse)(nil), // 11: record.RecordDeletedResponse
	(*RecordResponse)(nil),        // 12: record.RecordResponse
	(*RecordsResponse)(nil),       // 13: record.RecordsResponse
}
var file_api_grpc_proto_record_proto_depIdxs = []int32{
	0,  // 0: record.Record.password:type_name -> record.Password
	1,  // 1: record.Record.text:type_name -> record.Text
	2,  // 2: record.Record.binary:type_name -> record.Binary
	3,  // 3: record.Record.card:type_name -> record.Card
	0,  // 4: record.RecordCreateRequest.password:type_name -> record.Password
	1,  // 5: record.RecordCreateRequest.text:type_name -> record.Text
	2,  // 6: record.RecordCreateRequest.binary:type_name -> record.Binary
	3,  // 7: record.RecordCreateRequest.card:type_name -> record.Card
	0,  // 8: record.RecordUpdateRequest.password:type_name -> record.Password
	1,  // 9: record.RecordUpdateRequest.text:type_name -> record.Text
	2,  // 10: record.RecordUpdateRequest.binary:type_name -> record.Binary
	3,  // 11: record.RecordUpdateRequest.card:type_name -> record.Card
	4,  // 12: record.RecordResponse.record:type_name -> record.Record
	4,  // 13: record.RecordsResponse.records:type_name -> record.Record
	5,  // 14: record.Recorder.CreateRecord:input_type -> record.RecordCreateRequest
	10, // 15: record.Recorder.UpdateRecord:input_type -> record.RecordUpdatedResponse
	7,  // 16: record.Recorder.DeleteRecord:input_type -> record.RecordDeleteRequest
	8,  // 17: record.Recorder.GetRecord:input_type -> record.RecordGetRequest
	10, // 18: record.Recorder.GetRecords:input_type -> record.RecordUpdatedResponse
	9,  // 19: record.Recorder.CreateRecord:output_type -> record.RecordCreatedResponse
	10, // 20: record.Recorder.UpdateRecord:output_type -> record.RecordUpdatedResponse
	11, // 21: record.Recorder.DeleteRecord:output_type -> record.RecordDeletedResponse
	12, // 22: record.Recorder.GetRecord:output_type -> record.RecordResponse
	13, // 23: record.Recorder.GetRecords:output_type -> record.RecordsResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_record_proto_init() }
func file_api_grpc_proto_record_proto_init() {
	if File_api_grpc_proto_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_proto_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Password); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Binary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordUpdatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordDeletedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_record_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_grpc_proto_record_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Record_Password)(nil),
		(*Record_Text)(nil),
		(*Record_Binary)(nil),
		(*Record_Card)(nil),
	}
	file_api_grpc_proto_record_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*RecordCreateRequest_Password)(nil),
		(*RecordCreateRequest_Text)(nil),
		(*RecordCreateRequest_Binary)(nil),
		(*RecordCreateRequest_Card)(nil),
	}
	file_api_grpc_proto_record_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*RecordUpdateRequest_Password)(nil),
		(*RecordUpdateRequest_Text)(nil),
		(*RecordUpdateRequest_Binary)(nil),
		(*RecordUpdateRequest_Card)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_record_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_record_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_record_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_record_proto = out.File
	file_api_grpc_proto_record_proto_rawDesc = nil
	file_api_grpc_proto_record_proto_goTypes = nil
	file_api_grpc_proto_record_proto_depIdxs = nil
}
